services:
    fos_message.driver:
        class: FOS\Message\Driver\Doctrine\ORM\DoctrineORMDriver
        arguments: [ "@doctrine.orm.entity_manager" ]

    fos_message.repository:
        class: FOS\Message\Repository
        arguments: [ "@fos_message.driver" ]

    fos_message.event_dispatcher:
        class: FOS\Message\EventDispatcher\SymfonyBridgeEventDispatcher
        arguments: [ "@event_dispatcher" ]

    fos_message.tagger:
        class: FOS\Message\Tagger
        arguments:
            - "@fos_message.driver"
            - "@fos_message.repository"

    fos_message.sender:
        class: FOS\Message\Sender
        arguments:
            - "@fos_message.driver"
            - "@fos_message.event_dispatcher"

    app.form.data_trasnformer.recipients:
        class: AppBundle\Form\DataTransformer\RecipientsTransformer
        arguments:
            - "@fos_user.user_to_username_transformer"

    app.form.type.recipients:
        class: AppBundle\Form\Type\RecipientsType
        arguments:
            - "@app.form.data_trasnformer.recipients"
        tags:
            - { name: "form.type" }

    app.twig.extension.conversation_members:
        class: AppBundle\Twig\MessagesExtension
        arguments:
            - "@fos_message.repository"
        tags:
            - { name: "twig.extension" }
